version: 2
updates:
  # Flutter/Dart dependencies (pubspec.yaml)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(pub)"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
    open-pull-requests-limit: 3

  # Node.js tools (z. B. conventional-changelog)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(npm)"
    open-pull-requests-limit: 2
