name: sachkundenachweis
description: Vorbereitung auf den Sachkundenachweis nach LHundG NRW
version: 1.0.4+4
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management (für Multi-Theme und Co.)
  provider: ^6.1.2

  # Lokale Speicherung für Fortschritt & Theme
  shared_preferences: ^2.2.2

  # Fortschrittsanzeige (Diagramme, optional)
  fl_chart: ^1.0.0

  # Icons im Cupertino-Stil (optional)
  cupertino_icons: ^1.0.8

  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sketches/
    - assets/animations/trophy.json
    - assets/animations/firework.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
