name: sachkundenachweis
description: Vorbereitung auf den Sachkundenachweis nach LHundG NRW
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Lokale Speicherung
  shared_preferences: ^2.2.2

  # Fortschrittsanzeige (Diagramme)
  fl_chart: ^1.0.0

  # Icons im Cupertino-Stil (optional)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/