name: Feature request
description: Suggest an improvement
title: "[FEAT] <title>"
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Wanted change
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reason for change
    validations:
      required: true
